import pandas as pd
from fpdf import FPDF
import os
from datetime import datetime
import glob

# --- CONFIGURATION (PATH FIX) ---
import os
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
OUTPUT_DIR = os.path.join(PROJECT_ROOT, "outputs")
SCAN_FILE = os.path.join(PROJECT_ROOT, "data", "cleaned", "market_scan.csv")
NEWS_FILE = os.path.join(PROJECT_ROOT, "data", "cleaned", "daily_news_summary.txt")
TODAY_STR = datetime.now().strftime("%Y%m%d")

class MacroReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'MacroAI Institutional Scan', 0, 1, 'L')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 5, f'{datetime.now().strftime("%d %b %Y")}', 0, 1, 'L')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated by MacroAI Engine | Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(240, 240, 240)
        self.cell(0, 8, title, 0, 1, 'L', 1)
        self.ln(2)

    def chapter_body(self, body):
        self.set_font('Arial', '', 10)
        clean_body = str(body).encode('latin-1', 'replace').decode('latin-1')
        self.multi_cell(0, 5, clean_body)
        self.ln()

    def add_table(self, df):
        self.set_font('Arial', 'B', 9)
        # Headers
        cols = ['Ticker', 'Price', 'Trend', 'RSI', 'Mom_1M%']
        widths = [25, 30, 25, 20, 25]
        
        for i, col in enumerate(cols):
            self.cell(widths[i], 7, col, 1)
        self.ln()
        
        # Rows
        self.set_font('Arial', '', 9)
        for index, row in df.iterrows():
            # Ticker
            self.cell(widths[0], 7, str(row['Ticker']), 1)
            # Price
            self.cell(widths[1], 7, f"${row['Price']:,.2f}", 1)
            # Trend Color
            if row['Trend'] == 'BULL': self.set_text_color(0, 128, 0)
            else: self.set_text_color(200, 0, 0)
            self.cell(widths[2], 7, str(row['Trend']), 1)
            self.set_text_color(0)
            # RSI
            self.cell(widths[3], 7, str(int(row['RSI'])), 1)
            # Momentum
            self.cell(widths[4], 7, f"{row['Momentum_1M_%']:.1f}%", 1)
            self.ln()
        self.ln(5)

def load_news():
    if os.path.exists(NEWS_FILE):
        with open(NEWS_FILE, "r") as f:
            return f.read()
    return "No news summary found."

def generate_pdf():
    print(f"🚀 AGENT: Report Generator Initiated [{TODAY_STR}]")
    
    # 1. Load the massive scan
    if not os.path.exists(SCAN_FILE):
        print("❌ Scan file missing. Run Feature Engineer first.")
        return

    df = pd.read_csv(SCAN_FILE)
    
    # 2. Filter for "Top Picks"
    # Logic: BULL Trend + Strong Momentum + Not yet Overbought (RSI < 70)
    top_buys = df[
        (df['Trend'] == 'BULL') & 
        (df['RSI'] < 70) & 
        (df['Momentum_1M_%'] > 5)
    ].sort_values(by='Momentum_1M_%', ascending=False).head(10)

    # Logic: BEAR Trend + Weak Momentum + Not yet Oversold (RSI > 30)
    top_sells = df[
        (df['Trend'] == 'BEAR') & 
        (df['RSI'] > 30) & 
        (df['Momentum_1M_%'] < -5)
    ].sort_values(by='Momentum_1M_%', ascending=True).head(10)

    # 3. Market Breadth Stats
    bulls = len(df[df['Trend'] == 'BULL'])
    bears = len(df[df['Trend'] == 'BEAR'])
    total = len(df)
    breadth_pct = (bulls / total) * 100

    # 4. Build PDF
    pdf = MacroReport()
    pdf.add_page()
    
    # A. Market Pulse
    pdf.chapter_title("1. Global Market Pulse")
    pulse_text = (
        f"Assets Scanned: {total}\n"
        f"Market Breadth: {bulls} Bulls vs {bears} Bears ({breadth_pct:.1f}% Bullish)\n"
        f"Regime: {'Bullish Expansion' if breadth_pct > 60 else 'Bearish Contraction' if breadth_pct < 40 else 'Neutral / Rotation'}"
    )
    pdf.chapter_body(pulse_text)
    
    # B. News
    pdf.chapter_title("2. Geopolitical Context")
    pdf.chapter_body(load_news())

    # C. Top 10 Opportunities
    pdf.add_page()
    pdf.chapter_title("3. Top 10 Momentum Opportunities (Buy Candidates)")
    pdf.add_table(top_buys)

    pdf.chapter_title("4. Top 10 Breakdown Risks (Sell Candidates)")
    pdf.add_table(top_sells)

    # Save
    output_path = os.path.join(OUTPUT_DIR, f"Institutional_Scan_{TODAY_STR}.pdf")
    pdf.output(output_path, 'F')
    print(f"✅ Report Generated: {output_path}")

if __name__ == "__main__":
    generate_pdf()